#!/usr/bin/env python3
"""
OSINT Scanner wrapping FinalRecon (/home/themangahacker/FinalRecon/finalrecon.py)
Extracted data (subdomains, directories, emails, headers, endpoints, IP) is automatically
saved into DAGDIG StateManager to feed the LLM AI Analyzer pipeline.
"""
import os
import re
import sys
import shutil
import tempfile
import subprocess
from pathlib import Path
from urllib.parse import urlparse
from core.state import StateManager
from core.banner import print_status, print_good, print_warn, print_error

FINALRECON_SCRIPT = Path("/home/themangahacker/FinalRecon/finalrecon.py")

class OsintScanner:
    def __init__(self, state: StateManager):
        self.state = state

    def run_osint(self, target: str) -> dict:
        """
        Run FinalRecon on target (domain or IP/URL) and parse results into StateManager.
        """
        print_status(f"Starting FinalRecon OSINT scan on: {target}")

        if not FINALRECON_SCRIPT.exists():
            print_error(f"FinalRecon script not found at {FINALRECON_SCRIPT}")
            return {}

        # Format URL for FinalRecon
        if not target.startswith(("http://", "https://")):
            url = f"http://{target}"
        else:
            url = target

        # Create temporary dump directory for outputs
        temp_dir = tempfile.mkdtemp(prefix="dagdig_fr_")
        folder_name = "osint_dump"

        # Construct finalrecon command
        cmd = [
            sys.executable,
            str(FINALRECON_SCRIPT),
            "--url", url,
            "--headers",
            "--sslinfo",
            "--whois",
            "--dns",
            "--sub",
            "--dir",
            "--wayback",
            "-nb",
            "-cd", temp_dir,
            "-of", folder_name
        ]

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=300
            )
            raw_stdout = (result.stdout or "") + "\n" + (result.stderr or "")
            self.state.save_raw("osint_finalrecon", raw_stdout)

            # Parse console output
            self._parse_stdout(raw_stdout)

            # Parse exported files in dump directory
            dump_folder = Path(temp_dir) / folder_name
            if dump_folder.exists():
                self._parse_dump_folder(dump_folder)

            print_good("FinalRecon OSINT scan finished and parsed into state")
            self.state.save()
            return {"status": "success", "dump_dir": str(dump_folder)}

        except subprocess.TimeoutExpired:
            print_warn("FinalRecon OSINT scan timed out (5 mins)")
            return {"status": "timeout"}
        except Exception as e:
            print_error(f"FinalRecon OSINT execution failed: {e}")
            return {"status": "error", "error": str(e)}
        finally:
            try:
                shutil.rmtree(temp_dir, ignore_errors=True)
            except Exception:
                pass

    def _parse_stdout(self, text: str):
        """Extract IP, headers, subdomains, directories, emails directly from stdout."""
        # IP Address
        ip_match = re.search(r"IP Address\s*:\s*([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)", text)
        if ip_match:
            ip = ip_match.group(1)
            if not self.state.data.ip_address:
                self.state.data.ip_address = ip

        # Headers / Server technology hints
        server_match = re.search(r"Server\s*:\s*([^\n]+)", text, re.IGNORECASE)
        if server_match:
            srv = server_match.group(1).strip()
            if srv and srv not in self.state.data.technologies:
                self.state.data.technologies.append(f"Server: {srv}")

        # Emails
        emails = re.findall(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", text)
        for email in emails:
            if email.lower() not in [e.lower() for e in self.state.data.emails]:
                self.state.data.emails.append(email)

    def _parse_dump_folder(self, dump_dir: Path):
        """Parse txt/json files generated by FinalRecon."""
        for file_path in dump_dir.glob("*"):
            if file_path.is_file():
                try:
                    content = file_path.read_text(encoding="utf-8", errors="ignore")
                    fname = file_path.name.lower()

                    if "sub" in fname:
                        for line in content.splitlines():
                            sub = line.strip()
                            if sub and "." in sub:
                                self.state.data.add_subdomain(sub)

                    elif "dir" in fname:
                        for line in content.splitlines():
                            d = line.strip()
                            if d:
                                clean_d = d.lstrip("/")
                                self.state.data.add_directory(clean_d)

                    elif "wayback" in fname or "links" in fname:
                        for line in content.splitlines():
                            link = line.strip()
                            if link.startswith("http"):
                                if link not in self.state.data.endpoints:
                                    self.state.data.endpoints.append(link)

                    # Extract any emails present in dump files
                    emails = re.findall(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}", content)
                    for email in emails:
                        if email.lower() not in [e.lower() for e in self.state.data.emails]:
                            self.state.data.emails.append(email)

                except Exception as e:
                    print_warn(f"Failed parsing OSINT dump file {file_path.name}: {e}")
