#!/usr/bin/env python3
"""
Data models for DAGDIG
"""
from dataclasses import dataclass, field
from typing import List, Dict, Any

@dataclass
class Port:
    number: int
    protocol: str          # 'tcp' or 'udp'
    service: str = ''
    version: str = ''

    def __eq__(self, other):
        if not isinstance(other, Port):
            return False
        return (self.number == other.number and
                self.protocol == other.protocol and
                self.service == other.service)

@dataclass
class Service:
    name: str
    version: str = ''

    def __eq__(self, other):
        if not isinstance(other, Service):
            return False
        return self.name == other.name and self.version == other.version

@dataclass
class PageAnalysis:
    url: str
    auth_requirement: str = 'Public'        # 'Public' | 'Registration Page' | 'Auth Required (Login)' | 'Admin Protected'
    downloadable_files: List[str] = field(default_factory=list)
    technologies: List[str] = field(default_factory=list)
    summary: str = ''

    # --- Stage 2: Attack Surface Intelligence ---
    bypass_paths: List[str] = field(default_factory=list)
    """Paths that appear publicly accessible or are likely bypass candidates (e.g. /admin, /.git, /backup)."""

    auth_pages: List[str] = field(default_factory=list)
    """Paths that require account creation or login to access."""

    upload_points: List[Dict[str, str]] = field(default_factory=list)
    """File/source-code upload endpoints. Each entry: {path, method, field, note}."""

    download_points: List[str] = field(default_factory=list)
    """Downloadable file links or endpoints found on the page."""

    injectable_params: List[Dict[str, str]] = field(default_factory=list)
    """Tamperable URL params or form fields. Each entry: {param, location, example, risk}."""

    keyword_fingerprints: List[str] = field(default_factory=list)
    """Interesting words/product names/versions found in page content that could indicate vulnerabilities."""

    suspicious_items: List[str] = field(default_factory=list)
    """List of suspicious keywords, weird techniques, or anomaly items selected by Analyst for deep research."""

    # --- Stage 3: Exploit Research Output ---
    llm_recon_paragraph: str = ''
    """Concise recon paragraph generated by Stage 2 — fed into Stage 3 for CVE/exploit research."""

    research_tuples: List[Dict[str, Any]] = field(default_factory=list)
    """Structured list of (keyword/technique, research_findings) tuples returned by the Researcher."""

    exploit_report: Dict[str, Any] = field(default_factory=dict)
    """Final structured exploit report from Stage 3 containing CVEs, methods, tools, severity."""

    def to_dict(self) -> Dict[str, Any]:
        return {
            'url': self.url,
            'auth_requirement': self.auth_requirement,
            'downloadable_files': self.downloadable_files,
            'technologies': self.technologies,
            'summary': self.summary,
            'bypass_paths': self.bypass_paths,
            'auth_pages': self.auth_pages,
            'upload_points': self.upload_points,
            'download_points': self.download_points,
            'injectable_params': self.injectable_params,
            'keyword_fingerprints': self.keyword_fingerprints,
            'suspicious_items': self.suspicious_items,
            'llm_recon_paragraph': self.llm_recon_paragraph,
            'research_tuples': self.research_tuples,
            'exploit_report': self.exploit_report,
        }

    @classmethod
    def from_dict(cls, data: Dict) -> 'PageAnalysis':
        return cls(
            url=data.get('url', ''),
            auth_requirement=data.get('auth_requirement', 'Public'),
            downloadable_files=data.get('downloadable_files', []),
            technologies=data.get('technologies', []),
            summary=data.get('summary', ''),
            bypass_paths=data.get('bypass_paths', []),
            auth_pages=data.get('auth_pages', []),
            upload_points=data.get('upload_points', []),
            download_points=data.get('download_points', []),
            injectable_params=data.get('injectable_params', []),
            keyword_fingerprints=data.get('keyword_fingerprints', []),
            suspicious_items=data.get('suspicious_items', []),
            llm_recon_paragraph=data.get('llm_recon_paragraph', ''),
            research_tuples=data.get('research_tuples', []),
            exploit_report=data.get('exploit_report', {}),
        )

@dataclass
class TargetData:
    target: str = ''
    ip_address: str = ''
    open_ports: List[Port] = field(default_factory=list)
    protocols: List[str] = field(default_factory=list)
    services: List[Service] = field(default_factory=list)
    domains: List[str] = field(default_factory=list)
    subdomains: List[str] = field(default_factory=list)
    vhosts: List[str] = field(default_factory=list)
    directories: List[str] = field(default_factory=list)
    endpoints: List[str] = field(default_factory=list)
    parameters: List[str] = field(default_factory=list)
    technologies: List[str] = field(default_factory=list)
    page_analyses: List[PageAnalysis] = field(default_factory=list)
    emails: List[str] = field(default_factory=list)
    notes: str = ''
    timestamp: str = ''

    def to_dict(self) -> Dict[str, Any]:
        return {
            'target': self.target,
            'ip_address': self.ip_address,
            'open_ports': [p.__dict__ for p in self.open_ports],
            'protocols': self.protocols,
            'services': [s.__dict__ for s in self.services],
            'domains': self.domains,
            'subdomains': self.subdomains,
            'vhosts': self.vhosts,
            'directories': self.directories,
            'endpoints': self.endpoints,
            'parameters': self.parameters,
            'technologies': self.technologies,
            'page_analyses': [pa.to_dict() for pa in self.page_analyses],
            'emails': self.emails,
            'notes': self.notes,
            'timestamp': self.timestamp,
        }

    @classmethod
    def from_dict(cls, data: Dict) -> 'TargetData':
        td = cls(
            target=data.get('target', ''),
            ip_address=data.get('ip_address', ''),
            protocols=data.get('protocols', []),
            domains=data.get('domains', []),
            subdomains=data.get('subdomains', []),
            vhosts=data.get('vhosts', []),
            directories=data.get('directories', []),
            endpoints=data.get('endpoints', []),
            parameters=data.get('parameters', []),
            technologies=data.get('technologies', []),
            emails=data.get('emails', []),
            notes=data.get('notes', ''),
            timestamp=data.get('timestamp', ''),
        )
        for p in data.get('open_ports', []):
            td.open_ports.append(Port(**p))
        for s in data.get('services', []):
            td.services.append(Service(**s))
        for pa in data.get('page_analyses', []):
            td.page_analyses.append(PageAnalysis.from_dict(pa))
        return td

    def add_port(self, port: Port):
        if port not in self.open_ports:
            self.open_ports.append(port)
            if port.protocol not in self.protocols:
                self.protocols.append(port.protocol)

    def add_service(self, service: Service):
        if service not in self.services:
            self.services.append(service)

    def add_domain(self, domain: str):
        if domain not in self.domains:
            self.domains.append(domain)

    def add_subdomain(self, sub: str):
        if sub not in self.subdomains:
            self.subdomains.append(sub)

    def add_vhost(self, vhost: str):
        if vhost not in self.vhosts:
            self.vhosts.append(vhost)

    def add_directory(self, dir_path: str):
        if dir_path not in self.directories:
            self.directories.append(dir_path)
